name: Build site

# only run on changes to master
on: [push, pull_request]

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - run: make
    
    - name: Deploy to neocities
      if: ${{ success() && github.ref == 'refs/heads/main' }}
      id: deploy
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        dist_dir: _site

    - name: Deploy to Neocities fallback
      if: ${{ steps.deploy.outcome == 'failure' && github.ref == 'refs/heads/main' }}
      uses: jonchang/deploy-neocities@master
      with:
        key: ${{ secrets.NEOCITIES_API_KEY }}
        dir: _site
        clean: false